#!/bin/bash
# read in the stl filenames 
for badfilename in `find . -name "*t100_1*"` 
do
	echo $badfilename
	directory=`echo $badfilename | sed 's/\/knotplot100_1.vtk//'`
	filename=`echo $directory | sed 's/\.\///'`
	echo $directory	
	echo $filename	
	cd $directory
	jobid=`find . -name "*slurm*"`
	number=`echo $jobid | cut -c9-14`
pwd
	# kill everything
	scancel $number
	rm *.cpp *.h *.pbs *.vtk *.out *.txt;
	cd ..	
	# okay the job has been killed. lets rerun 
	cp myscript.pbs FN_knot_surface_openmp.cpp FN_knot_surface.h  $directory 
	cd $directory 
	# replace the filename with whatever the relevant filename is
	sed s/zero1/$filename/ FN_knot_surface_openmp.cpp > test.cpp 
	mv test.cpp FN_knot_surface_openmp.cpp
	# compile the code with this filename
	module load intel impi GSL 
	icpc -O3 -qopenmp FN_knot_surface_openmp.cpp -lgsl -lgslcblas -lm 
	# submit the compiled code to the cluster
	msub myscript.pbs 
	cd ..  
	
done 
