#!/bin/bash
# read in the stl filenames 
for filename in knotplot0_*.vtk 
do
	number=`echo $filename | sed 's/knotplot0_//'`
	number=`echo $number | sed 's/.vtk//'`
    #echo "${number}/11.2"
    dividednumber=$(bc <<< "${number}/11.2")
    cp $filename "knotplot0SCALED_${dividednumber}.vtk"
done 
