#!/bin/bash
# read in name/value pairs of the parameters by sourcing a file containing them
source parameters

# make a backup constants file before we do anything
cp FN_Constants.h FN_Constants_backup.h

# ok paste the values into the C code
names="INSERT_INITIALISATION_TYPE INSERT_SURFACE_FILENAME INSERT_UV_FILENAME INSERT_RUNTIME INSERT_UVPRINTTIME INSERT_VELOCITYPRINTTIME INSERT_FREQUENTPRINTTIME INSERT_SKIPTIME INSERT_GRIDSPACING INSERT_NX INSERT_NY INSERT_NZ INSERT_TIMESTEP"
for name in $names
do
    value=${!name}
    sed "s/${name}/${value}/" FN_Constants.h > temp
    mv -f temp FN_Constants.h
done

# now run make to compile
make
#clean up
mv -f FN_Constants.h FN_Constants_written.h
mv -f FN_Constants_backup.h FN_Constants.h


