#!/bin/awk -f
BEGIN {
	writhe=0;
	writheflag = 0;
	linesbelowwrithe = -1;

	Twist=0;
	Twistflag = 0;
	linesbelowTwist = -1;

	Length=0;
	Lengthflag = 0;
	linesbelowLength = -1;
}

{
	if($2=="Writhe"){ writheflag=1;}
	if(writheflag==1) linesbelowwrithe++ ; 
	if(linesbelowwrithe >1 && writheflag==1 && $2!="Twist" && $1 ){writhe+=$1;}

	if($2== "Twist") {writheflag=0; Twistflag=1; }
	if(Twistflag==1) linesbelowTwist++;
	if(linesbelowTwist >1 && Twistflag==1 && $2!="Length")Twist+=$1;

	if($2 == "Length") {Twistflag=0; Lengthflag=1;}
	if(Lengthflag==1) linesbelowLength++;
	if(linesbelowLength >1 && Lengthflag==1)Length+=$1;
}
END {
	printf("%f %f %f\n",writhe,Twist,Length);
}
