#!/bin/bash

# log the date we are run
date >> TinisRestartLog   

# read in the stl filenames 
for directoryname in {five2,five1}
do

	# go down into the folder
	cd $directoryname

	# first up, check if a job is currently running in this folder, or if there is one pending. we do this by looking through the list of jobs
	activejobsinthisdirectory=0
	for jobid in $(squeue -u matgqz -h -t PD,R -o %i)
	do

		jobdirectory=$(scontrol show job $jobid | grep "WorkDir*" | sed 's/WorkDir=\/tinisgpfs//')
		currentdir=$(pwd)

		if [ $currentdir == $jobdirectory ]; then
			activejobsinthisdirectory=1
		fi
	done

	# now, only do anything if there isnt an active job
	if [ $activejobsinthisdirectory -eq 0 ]; then

		# okay, first of all, how far did the code get? lets find the most recent uv_plot file
		latestuvvalue=$(ls | grep uv_plot | sed 's/.vtk//' | sed 's/uv_plot//' | sort -nr | head -1)
		uvFilename="uv_plot${latestuvvalue}.vtk"

		# ok we've got our uv filename which we want to restart the code from
		echo $uvFilename


		# okay, lets make a new parameters file, one which starts from the correct uv_file name
		# first up, clear the old parameters file which was in this directory 
        rm parameters
        rm FN_Constants.h

		cp ../jobrestartparameters .
		cp ../FN_Constants.h .

		# put the uv filename in
		sed "s/INSERT_UV_FILENAME/INSERT_UV_FILENAME=\"$uvFilename\"/" jobrestartparameters > parameters 
        
        ./CompilationScript
		startedjobid=$(msub myscript.pbs) 
	fi
	# okay we are done, lets change back out 
	cd ..

	# lets log what happened
	echo $directoryname >> TinisRestartLog   
	echo $activejobsinthisdirectory >> TinisRestartLog   
	echo $startedjobid >> TinisRestartLog   
	startedjobid=""
done
