#!/bin/bash

# cd into the top level directory
#cd /home/maths/matgqz/Knot_Surface/Knot_surface_calc/stable_configuration_simulations_23_06_2017
# log the date we are run
#date >> TinisRestartLog   

for directoryname in {five2,five1}
do
    # make a directory for the run, copy everything relevant into it	
    mkdir ${directoryname}
    cp Makefile CompilationScript jobstartparameters myscript.pbs *.cpp *.h  $directoryname 
    # grab the relevant file from the stl files Gareth made
    stlfilepath=`echo ./Knotplot_Evolver_files/stl/${directoryname}.stl`
    cp $stlfilepath $directoryname
    # now everything is in the folder, lets cd into it
    cd $directoryname

    # okay, lets modify the parameters file from the template, so we have the right filenames

    # set the surface filename 
    sed "s/^INSERT_SURFACE_FILENAME$/INSERT_SURFACE_FILENAME=\"${directoryname}\"/" jobstartparameters > parameters 

    # now we have made the parameters file, launch the pasting and compilation script
    ./CompilationScript
    # now its compiled, launch the job 
    #startedjobid=$(msub myscript.pbs) 
    # okay we are done, lets change back out 
    cd ..

    # lets log what happened
    #echo $filepath >> TinisRestartLog   
    #echo $activejobsinthisdirectory >> TinisRestartLog   
    #echo $startedjobid >> TinisRestartLog   
    #startedjobid=""

done


