#!/bin/bash
# read in the stl filenames 
for filepath in ~/Knot_Surface/Knot_surface_calc/Knotplot_Evolver_files/stl/{three1,three1alt,six2t,six3t,four1,four1_alt,five2,five2b,five1,five1_alt}.stl 
do
	filename=`echo $filepath | sed 's/.*\///'`
	filename=`echo $filename | sed 's/.stl//'`
	# make a directory for the run, copy everything relevant into it, then cd in	
	directoryname=${filename}	
	mkdir ${directoryname}
	cp myscript.pbs FN_knot_surface_openmp.cpp FN_knot_surface.h  $directoryname 
	# grab the relevant file from the stl files Gareth made
	cp $filepath $directoryname
	cd $directoryname
	# replace the filename with whatever the relevant filename is
	sed s/zero1/$filename/ FN_knot_surface_openmp.cpp > test.cpp 
	mv test.cpp FN_knot_surface_openmp.cpp
	# compile the code with this filename
	module load intel impi GSL 
	icpc -O3 -qopenmp FN_knot_surface_openmp.cpp -lgsl -lgslcblas -lm 
	# submit the compiled code to the cluster
	msub myscript.pbs 
	cd ..  
done 
