#!/bin/bash

# cd into the top level directory
cd /home/maths/matgqz/Knot_Surface/Knot_surface_calc/stable_configuration_simulations_23_06_2017
# log the date we are run
date >> TinisRestartLog   

# read in the stl filenames 
for filepath in /home/maths/matgqz/Knot_Surface/Knot_surface_calc/stable_configuration_simulations_23_06_2017/{five2,five2b,five1,five1_alt,six1,six2,six3,seven1,seven2,seven6,seven7}
do

	# go down into the folder
	cd $filepath

	# first up, check if a job is currently running in this folder. we do this by looking through the list of jobs
	activejobsinthisdirectory=0
	for jobid in $(squeue -u matgqz -h -t R -o %i)
	do

		jobdirectory=$(scontrol show job $jobid | grep "WorkDir*" | sed 's/WorkDir=\/tinisgpfs//')
		currentdir=$(pwd)

		if [ $currentdir == $jobdirectory ]; then
			activejobsinthisdirectory=1
		fi
	done
	# now, only do anything if there isnt an active job
	if [ $activejobsinthisdirectory -eq 0 ]; then

		# okay, first of all, how far did the code get? lets find the most recent uv_plot file
		latestuvvalue=$(ls | grep uv_plot | sed 's/.vtk//' | sed 's/uv_plot//' | sort -nr | head -1)
		uvFilename="uv_plot${latestuvvalue}.vtk"

		# ok we've got our uv filename which we want to restart the code from
		# first grab some details. what dimensions should we use?
		dimension=$(head -5 $uvFilename | tail -1 | awk '{print $2}')
		echo $dimension
		echo $uvFilename


		# okay, lets go into the C code, make these substitutions, and recompile the code

		# first up, copy the templated code in here
		cp ../FN_Constants.h .

		# If its set on FROM_SURFACE_FILE, change that
		sed 's/INSERT_INITIALISATION_TYPE/FROM_UV_FILE/' FN_Constants.h > temp
		mv temp FN_Constants.h 
		# put the uv filename in
		sed "s/INSERT_UV_FILENAME/\"$uvFilename\"/" FN_Constants.h > temp 
		mv temp FN_Constants.h 
		# change the dimensions
		sed "s/INSERT_NX/$dimension/" FN_Constants.h > temp 
		mv temp FN_Constants.h 
		sed "s/INSERT_NY/$dimension/" FN_Constants.h > temp 
		mv temp FN_Constants.h 
		sed "s/INSERT_NZ/$dimension/" FN_Constants.h > temp 
		mv temp FN_Constants.h 
		# change the skiptime settings
		sed "s/INSERT_SKIPTIME/0/" FN_Constants.h > temp 
		mv temp FN_Constants.h 
		# change the total desired runtime
		sed "s/INSERT_RUNTIME/20000/" FN_Constants.h > temp 
		mv temp FN_Constants.h 

		# compile the code with this filename
		module load intel impi GSL 
		icpc -O3 -qopenmp FN_Knot.cpp TriCubicInterpolator.cpp -lgsl -lgslcblas -lm	
		startedjobid=$(msub myscript.pbs) 
	fi
	# okay we are done, lets change back out 
	cd ..

	# lets log what happened
	echo $filepath >> TinisRestartLog   
	echo $activejobsinthisdirectory >> TinisRestartLog   
	echo $startedjobid >> TinisRestartLog   
	startedjobid=""

done


